### PR TITLE
Drop support for camptocamp archive provider

### PR DESCRIPTION
**Pull request by ekohl**
This module has been archived and was already deprecated. Dropping this simplifies the module.

### CODE REVIEW

**Comment by ekohl** [comment]
I haven't tested this myself, relying on tests. My goal is to drop as much as possible from .sync.yml and modulesync configs.

I didn't update the HTML docs directory since I couldn't generate it. I'm wondering if we should keep this or stick to REFERENCE.md.

**Comment by Dan33l** [comment]
> I haven't tested this myself, relying on tests. My goal is to drop as much as possible from .sync.yml and modulesync configs.
> 
> I didn't update the HTML docs directory since I couldn't generate it. I'm wondering if we should keep this or stick to REFERENCE.md.
Have only one format avoids that one of them is not up to date, since files are not automatically generated.
And REFERENCE.md is the current standard way that users of module expect.

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-virtualbox/pull/116 does that.

**Comment by ekohl** [comment]
Rebased with some more things I missed (README and acceptance).

**Review by bastelfreak — APPROVED** [review]

**Pull request merged**
