### PR TITLE
[WIP] Enable acceptance tests

### PR DESCRIPTION
**Pull request by bastelfreak**
@dan33l, are you interested in taking a look at this as well? I just noticed that the module ship acceptance tests, we just didn't enable them.

### CODE REVIEW

**Comment by Dan33l** [comment]
If we remove old OSes i can looks at acceptance tests.
So i propose to remove ubuntu 14.04 and to add ubuntu 16.04 and 18.04.
If you agree, i create an issue about this.

**Comment by bastelfreak** [comment]
dropping 14.04 is totally fine.

**Comment by Dan33l** [comment]
WIP PR #71 proposed about up to date acceptance tests.

**Comment by Dan33l** [comment]
The reason given by installer : `vboxdrv.sh: failed: Running VirtualBox in a Xen environment is not supported.`

**Comment by alexjfisher** [comment]
@bastelfreak This can be closed?

**Comment by Dan33l** [comment]
Enable acceptance tests is not possible with our current setup.  For this module, we can't use a container.

**Pull request closed without merging**
